spring.application.name=CattleFyApi

#spring.datasource.url=jdbc:postgresql://localhost:5432/DB_CATTLEFY
#spring.datasource.username=postgres
#spring.datasource.password=sqlpostgre

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#Crea variables de entorno en tu pc para q te lea estos valores

cloudinary.name = {CLOUDINARY_NAME}
cloudinary.key = {CLOUDINARY_KEY}
cloudinary.secret = {CLOUDINARY_SECRET}